### ISSUE TITLE
On 2 columns setup map opens 'in the back'

### ISSUE THREAD

**Issue by kaste** [oleg-shilo/sublime-codemap#2]
I have a 2 columns setup, being on the right (second) column the following happens: 

![fkx1bat3bq](https://cloud.githubusercontent.com/assets/8558/22924603/10365b32-f2a6-11e6-91a2-2d0c63a571e2.gif)

I would rather expect that a 3rd column opens. At least the map should be visible.

**Comment by oleg-shilo** [comment]
Thank you. Will work on it. 

Unfortunately there is a limit on how much can be done for custom vertical panels in ST. I would rather use some sort of a true sidebar instead of mimicking it with a text view. Anyway, I had to impose a rather unpleasant constraint - CodeMap is always placed in the column '2' and it reflects the code in the column '1'. I just don't see any other way.
  
Though your point stands. `Toggle Visibility' should bring the view on top of other views.

**Comment by kaste** [comment]
It basically works with 3 columns. And you can get this to work with some sublime Fu and more coding of course ... 😼 
![nfjutby6ry](https://cloud.githubusercontent.com/assets/8558/22925580/904cccb8-f2a9-11e6-8a73-0f4175a8ecfe.gif)
.

**Comment by oleg-shilo** [comment]
I have submitted the fix so you can get it from github. But I haven't created the tag just yet so probably you need to bring it manually if you don't want to wait.

The fix ensures that after showing the CodeMap view it stays on top. 

As for 3-column layout, yes I expect it to work as it is. The reason for 2-nd column constraint is that I see no ideal user experience so I have to place codemap view somewhere outside of the first group (e.g. column 2).  

May be I will come up with something better after some user feedback :)

**Comment by oleg-shilo** [comment]
The latest release (v1.0.2) has the following change to address the User Experience limitations:
>The CodeMap view is always placed in the most right column (group) of the active window. If the layout has only a single column then the plugin automatically switches in the "2-columns" layout. You can also configure plugin (via setting 'close_empty_group_on_closing_map') to hide the group on closing the CodeMap view when it is the only view in the group.

The release/update is tagged so it can be retrieved via Repository channel in ST3.

**Comment by kaste** [comment]
Will try it on next sublime restart
