### ISSUE TITLE
For other editor?

### ISSUE THREAD

**Issue by Alexey-T** [oleg-shilo/sublime-codemap#3]
Hi Oleg
seems, good plugin, tks.
Can i make you donation, to port it to CudaText?

**Comment by oleg-shilo** [comment]
Hi Alexey,

I assume you are not talking about a money donation? Are you? :)

If it is about a code contribution then tell me what exactly do you have in mind. What is involved in porting? Does CudaText uses the same plugin hosting model as ST3?

**Comment by Alexey-T** [comment]
I talk about $ donation too (if you want)
Porting for Cud is using new API (python) of Cud. it has not the same model.

**Comment by Alexey-T** [comment]
i see now: it is like Cudatext Tree panel (on the left)? How it is different from Tree panel...

**Comment by oleg-shilo** [comment]
Sorry Alexey, I am afraid I am stressed out with my other projects and don't really have time for any active development of CodeMap.

**Comment by Alexey-T** [comment]
Ok, thanks
