### ISSUE TITLE
How to remove the CodeMap strip without uninstalling the CodeMap Plug-In?

### ISSUE THREAD

**Issue by ldm1417** [oleg-shilo/sublime-codemap#39]
Hi, 
How to remove the CodeMap strip without uninstalling the CodeMap Plug-In? 
Thanks!

**Comment by oleg-shilo** [comment]
I am not sure what you referring to. Do you mean "CodeMap strip" the tab with the map:
![image](https://user-images.githubusercontent.com/16729806/152331744-55addfd1-6024-4637-9494-6800b1a05200.png)

If it is the case then you can just close this tab.
But most likely it is not that...
